spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Jandaes/SpringCloudConfig.git
          search-paths: respo
          # ¹«¿ª²Ö¿â²»ÓÃÌîĞ´ÕÊºÅÃÜÂë
          #username:
          #passphrase:
      label: master
server:
  port: 8888